### ISSUE TITLE
[FEATURE] Rebuild kextcache after patching

### ISSUE THREAD

**Issue by thejsa** [julian-fairfax/osx-sl-patcher#2]
**Is your feature request related to a problem? Please describe.**
The patcher tool (understandably) deletes the kextcache, but does not rebuild it after replacing kexts, complicating network installation.

**Describe the solution you'd like**
Add a line to rebuild the kextcache (Extensions.mkext) after patching, if possible, to enable easy netbooting.

**Comment by julian-fairfax** [comment]
I didn't think of the netboot possibility. I'll look into adding this.
